export const SetUser = 'SetUser'
export const SetData = 'SetData'
export const SetToken = 'SetToken'
export const SetRefreshToken = 'SetRefreshToken'
export const SetExpiresIn = 'SetExpiresIn'
export const SetTokenId = 'SetTokenId'
