export const FetchStudents = 'FetchStudents'
export const AddStudent = 'AddStudent'
export const UpdateStudent = 'UpdateStudent'
export const RemoveStudent = 'RemoveStudent'
export const EditStudent = 'EditStudent'