export const SetStudent = 'SetStudent'
export const GetStudents = 'GetStudents'
export const DeleteStudent = 'DeleteStudent'
export const UpdateStudent = 'UpdateStudent'
export const  SetEditStatus = 'SetEditStatus'
export const SetTitle = 'SetTitle'