export const SetStudent = 'SetStudent'
export const GetStudent = 'GetStudent'
export const UpdateStudent = 'UpdateStudent'
export const SetEditStatus = 'SetEditStatus'
export const SetTitle = 'SetTitle'
export const SetTotalCount = 'SetTotalCount'