export const SetBatch = 'SetBatch'
export const GetBatch = 'GetBatch'
export const DeleteBatch = 'DeleteBatch'
export const UpdateBatch = 'UpdateBatch'
export const  SetEditStatus = 'SetEditStatus'
export const SetTitle = 'SetTitle'
export const SetTotalBatchCount = 'SetTotalBatchCount'