export const SetContacts = 'SetContacts'
export const DeleteContact = 'DeleteContact'
export const SetEditContact = 'SetEditContact'
export const SetContactAlertStatus = 'SetContactAlertStatus'
export const SetContactAlertText = 'SetContactAlertText'
